"""Initial migration

Revision ID: fbf6f979f345
Revises: 2db20a9b9e31
Create Date: 2025-07-04 16:50:24.608545

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fbf6f979f345"
down_revision = "2db20a9b9e31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("conn", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "conn")
    # ### end Alembic commands ###
