"""Initial migration

Revision ID: 9f2353f55516
Revises: 350eb1709908
Create Date: 2025-06-25 23:26:50.813500

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f2353f55516"
down_revision = "350eb1709908"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("diag_price", sa.Float(), nullable=True))
    op.add_column("application", sa.Column("mechanic_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "mechanic_price")
    op.drop_column("application", "diag_price")
    # ### end Alembic commands ###
