"""Initial migration

Revision ID: 350eb1709908
Revises: 60347414afda
Create Date: 2025-06-24 14:11:51.788861

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "350eb1709908"
down_revision = "60347414afda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "arrival_time")
    # ### end Alembic commands ###
