"""Initial migration

Revision ID: 655303341c42
Revises: 380074353934
Create Date: 2025-07-29 14:53:28.241895

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "655303341c42"
down_revision = "380074353934"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("car", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("car", "is_deleted")
    # ### end Alembic commands ###
