"""Initial migration

Revision ID: fce7511b5c43
Revises: 9f2353f55516
Create Date: 2025-06-25 23:29:00.495198

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fce7511b5c43"
down_revision = "9f2353f55516"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("pay_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "pay_at")
    # ### end Alembic commands ###
