"""Initial migration

Revision ID: 380074353934
Revises: fbf6f979f345
Create Date: 2025-07-10 02:41:40.059756

"""


from alembic import op

# revision identifiers, used by Alembic.
revision = "380074353934"
down_revision = "fbf6f979f345"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("application_client_id_fkey"), "application", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("application_car_id_fkey"), "application", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "application", "client_account", ["client_id"], ["client_id"]
    )
    op.create_foreign_key(None, "application", "car", ["car_id"], ["id"])
    op.drop_constraint(op.f("car_client_id_fkey"), "car", type_="foreignkey")
    op.create_foreign_key(None, "car", "client_account", ["client_id"], ["client_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "car", type_="foreignkey")
    op.create_foreign_key(
        op.f("car_client_id_fkey"),
        "car",
        "client_account",
        ["client_id"],
        ["client_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_constraint(None, "application", type_="foreignkey")
    op.create_foreign_key(
        op.f("application_car_id_fkey"),
        "application",
        "car",
        ["car_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("application_client_id_fkey"),
        "application",
        "client_account",
        ["client_id"],
        ["client_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
