"""Initial migration

Revision ID: 60347414afda
Revises:
Create Date: 2025-06-23 17:16:16.558619

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "60347414afda"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_account",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "DIAGNOSTIC", "ADMIN", "MECHANIC", "SUPERADMIN", "CLIENT", name="role"
            ),
            nullable=False,
        ),
        sa.Column("user_name", sa.String(length=256), nullable=True),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "car",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(length=256), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("number", sa.String(length=256), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client_account.client_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.String(length=512), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("exp", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_refresh_token"),
        "refresh_token",
        ["refresh_token"],
        unique=True,
    )
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("problem", sa.String(), nullable=True),
        sa.Column("admin_comment", sa.String(), nullable=True),
        sa.Column("diag_comment", sa.String(), nullable=True),
        sa.Column("mechanic_comment", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "CARWAITING",
                "DIAGNOSTIC",
                "REPAIR",
                "READY",
                "REJECTED",
                "COMPLETED",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="priority"),
            nullable=False,
        ),
        sa.Column("diag_id", sa.Integer(), nullable=True),
        sa.Column("mechanic_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["car.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client_account.client_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["diag_id"],
            ["user_account.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["mechanic_id"],
            ["user_account.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment",
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("card", "cash", "unknown", name="method"),
            nullable=True,
        ),
        sa.Column("pay_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("application_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment")
    op.drop_table("application")
    op.drop_index(op.f("ix_refresh_token_refresh_token"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_table("car")
    op.drop_table("user_account")
    op.drop_table("client_account")
    # ### end Alembic commands ###
